# Generated by Django 6.1 on 2026-09-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novatask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache_projet',
            name='fonctionnalite',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tache_projet',
            name='resultat_attendu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='tache_projet',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resultat_attendu__isnull', False), ('fonctionnalite__isnull', True)), models.Q(('resultat_attendu__isnull', True), ('fonctionnalite__isnull', False)), _connector='OR'), name='soit_a_soit_b_pas_les_deux'),
        ),
    ]
