# Generated by Django 6.1 on 2026-09-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novatask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='id_proj',
            field=models.CharField(editable=False, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='tache_projet',
            name='num_tache',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
