# Generated by Django 6.1 on 2026-09-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novatask', '0002_alter_projet_id_proj_alter_tache_projet_num_tache'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache_projet',
            name='rappel_envoye',
            field=models.BooleanField(default=False),
        ),
    ]
