# Generated by Django 6.1 on 2026-09-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novatask', '0002_tache_projet_fonctionnalite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache_projet',
            name='fonctionnalite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='id_user',
            field=models.CharField(editable=False, max_length=5, unique=True),
        ),
    ]
