# Generated by Django 6.1 on 2026-09-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novatask', '0003_tache_projet_rappel_envoye'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache_projet',
            name='priorite',
            field=models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute')], default='normale', max_length=10),
        ),
    ]
